// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1595010523);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1595011239);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1595029799);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1595007657);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1595010403);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1595011479);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1595011359);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 33137);
user_pref("browser.cache.disk.capacity", 942080);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1595007507);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8a8abe1a-e1f1-4870-ac84-ed12ae7968d3}");
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1595031584553");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1595033388553");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1595029799679");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1595033399679");
user_pref("browser.search.region", "PE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200403171148");
user_pref("browser.slowStartup.averageTime", 7714);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20200403171148");
user_pref("browser.startup.homepage_override.mstone", "68.7.0");
user_pref("browser.startup.lastColdStartupCheck", 1595029772);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.7.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Tue, 14 Jul 2020 18:25:32 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1595010524);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200403171148");
user_pref("extensions.lastAppVersion", "68.7.0");
user_pref("extensions.lastPlatformVersion", "68.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.privatebrowsing.notification", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"5b07be08-c7a9-4566-8946-7c902e308f06\",\"fxmonitor@mozilla.org\":\"a8e0af07-213d-4eae-8834-251954298824\",\"screenshots@mozilla.org\":\"43afe752-48b9-4833-b71e-86250a7589da\",\"webcompat-reporter@mozilla.org\":\"e2392e26-6f3c-451b-8a8c-734228b9ff49\",\"webcompat@mozilla.org\":\"b5db7265-a974-4589-8b98-8ad2d3face93\",\"default-theme@mozilla.org\":\"ceb9dbbd-09a6-4420-879d-de97cb026e27\",\"google@search.mozilla.org\":\"62214fc2-56d4-49e3-a216-2778eacc97aa\",\"amazondotcom@search.mozilla.org\":\"fcafef40-2096-4a67-9aa2-5abc7bb801c6\",\"bing@search.mozilla.org\":\"64f629fe-97f6-4699-886f-e020856f089e\",\"ddg@search.mozilla.org\":\"7d76cfe2-35a8-47eb-8dc7-a88850973db1\",\"ebay@search.mozilla.org\":\"b2726402-c00c-470b-9b42-5b6a9afa11c5\",\"twitter@search.mozilla.org\":\"5c9a77b7-4a68-4df7-a2b8-673993958e54\",\"wikipedia@search.mozilla.org\":\"10ed7b40-c296-4ab2-a5ee-e07d4c4851e4\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1595030752);
user_pref("media.gmp-manager.buildID", "20200403171148");
user_pref("media.gmp-manager.lastCheck", 1595007692);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1595030752);
user_pref("places.history.expiration.transient_current_max_pages", 89154);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "e2f45c74-b108-4cfb-8f20-fe31bbb0eb11");
user_pref("security.sandbox.plugin.tempDirSuffix", "79d817c4-335f-4ee3-b4a5-c59c757621ce");
user_pref("services.blocklist.pinning.checked", 1595010405);
user_pref("services.settings.clock_skew_seconds", -2);
user_pref("services.settings.last_update_seconds", 1595010405);
user_pref("services.settings.main.cfr-fxa.last_check", 1595010405);
user_pref("services.settings.main.cfr.last_check", 1595010405);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1595010405);
user_pref("services.settings.main.hijack-blocklists.last_check", 1595010405);
user_pref("services.settings.main.language-dictionaries.last_check", 1595010405);
user_pref("services.settings.main.sites-classification.last_check", 1595010405);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1595010405);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1595030752);
user_pref("toolkit.startup.last_success", 1595029764);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200403171148");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
